url: "http://ustroetz.github.io"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true


prose:
  siteurl: "http://ustroetz.github.io"
  media: "images"
  ignore:
    - CNAME
    - css
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
